language: go

go:
  - 1.9

services:
  - docker
env:
  - DEP_VERSION="0.4.1"
  - PATH="$PATH:$GOPATH/bin"
before_install:
  # Install dep
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure --vendor-only
  - go install ./vendor/gopkg.in/bblfsh/sdk.v1/...
before_script:
  - bblfsh-sdk prepare-build .

script:
  - make test integration-test

after_success:
  - make push
