language: go

go:
  - 1.9

services:
  - docker
env:
  - DEP_VERSION="0.4.1"
before_install:
  - export PATH=$GOPATH/bin:$PATH
  # Install dep
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure --vendor-only
  - go install -v ./vendor/gopkg.in/bblfsh/sdk.v1/...
  - ls $GOPATH/bin && echo $GOPATH/bin && echo $PATH/bin
before_script:
  - bblfsh-sdk prepare-build .

script:
  - make test integration-test

after_success:
  - make push
